spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/simple_storage?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

logging:
  level: debug

server:
  port: 8088