spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/**

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.kchen.storage.dao.domain.common
  configuration:
      map-underscore-to-camel-case: true