spring:
  profiles:
    active: dev
  datasource:
      name: default
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 10000
      initialSize: 10
      maxWait: 6000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.kchen.storage.dao.domain.common
  configuration:
      map-underscore-to-camel-case: true