spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenkunyun/simple-storage
          search-paths: simple-storage-config-repo
          username: xxx
          password: xxx

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/