spring:
  mvc:
    static-path-pattern: /resources/**
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  sleuth:
      zuul:
        enabled: true
      sampler:
        percentage: 1.0