spring:
  application:
    name: api-gateway
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
    zuul:
      enabled: true

server:
  port: 5555

zuul:
  routes:
    rest:
      path: /rest/**
      serviceId: rest-api
    search:
      path: /search/**
      serviceId: rest-api-search
    php:
      path: /php/**
      serviceId: sidecar-php

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
