spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /resources/**
  application:
    name: rest-api-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
